Fix C++23 build failure in libberberis_base
Add <cstring> include for memcpy declaration.
This fixes errors with C++23 because it removed transitive includes.

Errors:
frameworks/libs/binary_translation/base/exec_region.cc:30:3: error: use
of undeclared identifier 'memcpy'; did you mean 'wmemcpy'?
   30 |   memcpy(write_ + offset, src, size)

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libberberis_base
Change-Id: I2f969c6a437ac69ebed776768e6fea9e5b8e8805