[C++23] Add missing C++23 headers
Add tuple header to fix C++23 build errors because C++23 removed some
transitive includes

Error:
frameworks/libs/binary_translation/guest_abi/arm64/include/berberis/guest_abi/guest_params_arch.h:99:3:
error: implicit instantiation of undefined template
'std::tuple<berberis::arm64::CallingConventions,
std::array<berberis::arm64::ArgLocation, 3>>'
   99 |   ParamsInfoHelper() {
frameworks/libs/binary_translation/guest_abi/arm64/include/berberis/guest_abi/guest_params_arch.h:123:12:
error: implicit instantiation of undefined template
'std::tuple<berberis::arm64::CallingConventions,
std::array<berberis::arm64::ArgLocation, 3>>'
  123 |     return {conv, result};

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libndk_translation_proxy_libc
Change-Id: Ib190724f08b414baf2c441faa153f3b30b1c0515