[C++23] berberis: Add missing tuple header
Add tuple to fix C++23 build errors because C++23 removed certain
transitive includes

Error:
frameworks/libs/binary_translation/guest_abi/arm/include/berberis/guest_abi/guest_params_arch.h:122:3:
error: implicit instantiation of undefined template
'std::tuple<berberis::arm::CallingConventions,
std::array<berberis::arm::ArgLocation, 3>>'
  122 |   ParamsInfoHelper() {

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libndk_translation_kernel_api
Change-Id: Ieca593ded4724eb9e4c60fb6463c318cd641b492